### ISSUE TITLE
Build for sles 12.4 needed

### ISSUE THREAD

**Issue by roebert** [wkhtmltopdf/packaging#38] opened 2019-10-23 11:30 UTC
Hello,

we need the 0.12.5 on a SLES 12.4 server.
i downloaded the sources and if i get this right i would need a docker image for sles 12.4 which i cant find - so no possibility to compile this?!

with best regards, roebert

**Comment by ashkulz** [comment] 2019-10-25 12:13
See #27 on a WIP build for OpenSUSE -- which should be pretty similar. If there's no docker image, I'm not sure how you can compile for it 🤷‍♂

**Comment by ashkulz** [comment] 2020-06-02 13:00
Duplicate of #22

**Closed by ashkulz** 2020-06-02 13:00 UTC
Labels: help wanted

**Comment by ashkulz** [comment] 2020-06-06 20:40
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
