### ISSUE TITLE
missing linux-generic

### ISSUE THREAD

**Issue by Pulsar-san** [wkhtmltopdf/packaging#16] opened 2018-12-05 21:27 UTC
I don't find the linux-generic-amd64.tar.xz package for the 0.12.5

**Comment by Tomsgu** [comment] 2018-12-06 16:11
This issue already exists https://github.com/wkhtmltopdf/packaging/issues/8

**Comment by ashkulz** [comment] 2019-03-25 12:35
Duplicate of #8

**Closed by ashkulz** 2019-03-25 12:35 UTC
