### ISSUE TITLE
wkhtmltopdf on Debian 11

### ISSUE THREAD

**Issue by Kaias26** [wkhtmltopdf/packaging#110] opened 2022-03-18 15:55 UTC
Hi !
I'am a web developper and i've started to use wkhtmltopdf for a project.
My testing environnement is a Debian 10 and the package from gitHub works well. 
But my production server is a Debian 11 and the package doesn't seems to include the "QT patch" thing.

My biggest problem is that --header and --footer arguments doesen't works at all.

I'am not famillar with linux or qt or packaging, but is there a way to use the patched qt on my Debian 11 ?
any tips are welcolme.

Thx !

**Comment by ashkulz** [comment] 2022-03-20 06:24
Duplicate of #99 -- the Debian 10 build should work as-is.

**Closed by ashkulz** 2022-03-20 06:24 UTC

**Comment by ashkulz** [comment] 2022-06-23 06:20
Builds have been published to the website: see wkhtmltopdf/wkhtmltopdf@e59bfcce3e8db83341264bdd75d996319402ccff.
